package com.project.pojo;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * OrderLog generated by hbm2java
 */
@Entity
@Table(name = "order_log")
public class OrderLog implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
	private String id;
	
	/** 行为 */
	private String behavioutDescribe;
	
	/** 创建时间*/
	private Date createTime = new Date();
	
	/** 日志类型 1 订单操作日志 2 订单售后日志 3 订单退款申请日志 4 订单正常流程跟踪 */
	private Integer logType;
	
	/** 操作结果 1 表示成功 2 失败*/
	private Integer operateResult = 1;
	
	/** 操作人*/
	private String operateUser;
	
	/** 订单编号*/
	private String orderNo;
	
	/** 备注*/
	private String remark;

    /** 售后单id */
    private String            applyId;

    public OrderLog() {
    }

    public OrderLog(String id) {
        this.id = id;
    }
    
    
    
    public OrderLog(String behavioutDescribe, Integer logType,
			Integer operateResult, String operateUser, String orderNo,
			String applyId) {
		this.behavioutDescribe = behavioutDescribe;
		this.logType = logType;
		this.operateResult = operateResult;
		this.operateUser = operateUser;
		this.orderNo = orderNo;
		this.applyId = applyId;
	}

	public OrderLog(String id, String behavioutDescribe, Date createTime, Integer logType, Integer operateResult,
                    String operateUser, String orderNo, String applyId, String remark) {
        super();
        this.id = id;
        this.behavioutDescribe = behavioutDescribe;
        this.createTime = createTime;
        this.logType = logType;
        this.operateResult = operateResult;
        this.operateUser = operateUser;
        this.orderNo = orderNo;
        this.applyId = applyId;
        this.remark = remark;
    }

    @GenericGenerator(name = "generator", strategy = "uuid.hex")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "id", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "behaviout_describe", length = 50)
    public String getBehavioutDescribe() {
        return this.behavioutDescribe;
    }

    public void setBehavioutDescribe(String behavioutDescribe) {
        this.behavioutDescribe = behavioutDescribe;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "log_type")
    public Integer getLogType() {
        return this.logType;
    }

    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    @Column(name = "operate_result")
    public Integer getOperateResult() {
        return this.operateResult;
    }

    public void setOperateResult(Integer operateResult) {
        this.operateResult = operateResult;
    }

    @Column(name = "operate_user", length = 32)
    public String getOperateUser() {
        return this.operateUser;
    }

    public void setOperateUser(String operateUser) {
        this.operateUser = operateUser;
    }

    @Column(name = "order_no", length = 32)
    public String getOrderNo() {
        return this.orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    @Column(name = "remark", length = 400)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Column(name = "apply_id", length = 32)
	public String getApplyId() {
		return applyId;
	}

	public void setApplyId(String applyId) {
		this.applyId = applyId;
	}

}
